[build]
  command = "npm run build && node generate-sitemap.cjs && node generate-rss.cjs"
  publish = "dist"

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news-proxy"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/popular-stocks"
  to = "/.netlify/functions/popular-stocks"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/*"
  to = "https://stock-lab-backend-repo.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
