name: Upload daily stock prices

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  upload:
    name: Scrape and upload prices
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload daily prices
        env:
          SERVICE_ACCOUNT_KEY_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          PAGES_TO_SCRAPE: '1'
        run: python daily_price_uploader.py
